### ISSUE TITLE
打包失败问题

### ISSUE THREAD

**Issue by houchangming** [yxw007/QRCodeTools#1]
npm run build:win
打包错误

**Comment by yxw007** [comment]
> npm run build:win 打包错误

最新的版本已修复，如果还有错误，麻烦把你打包出错的日志贴出来看下

**Comment by houchangming** [comment]
⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by yxw007** [comment]
> ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.⨯ 获取“https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z”：拨打 tcp 20.205.243.166：443：connectex：连接尝试失败，因为连接方在一段时间后没有正确响应，或者建立的连接失败，因为连接的主机无法响应。

网络问题，这个打包需要翻墙。如果只是先体验一下，可以clone 下来，运行看下。
```shell
yarn 
yarn dev
```

**Comment by yxw007** [comment]
> ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

已经发布了，可以下载exe体验

下载地址：
https://github.com/yxw007/QRCodeTools/releases/tag/v1.0.0-6

使用文档：
https://github.com/yxw007/QRCodeTools
